# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 821)
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_show = QtWidgets.QTabWidget(self.widget)
        self.tab_show.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tab_show.setFont(font)
        self.tab_show.setAutoFillBackground(False)
        self.tab_show.setObjectName("tab_show")
        self.tab_detection_scenario = QtWidgets.QWidget()
        self.tab_detection_scenario.setEnabled(True)
        self.tab_detection_scenario.setAutoFillBackground(False)
        self.tab_detection_scenario.setObjectName("tab_detection_scenario")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_detection_scenario)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gl_detection_scenario = QtWidgets.QGridLayout()
        self.gl_detection_scenario.setObjectName("gl_detection_scenario")
        self.gridLayout_2.addLayout(self.gl_detection_scenario, 0, 0, 1, 1)
        self.tab_show.addTab(self.tab_detection_scenario, "")
        self.tab_magnetic_field_data = QtWidgets.QWidget()
        self.tab_magnetic_field_data.setObjectName("tab_magnetic_field_data")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_magnetic_field_data)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gl_magnetic_field_data = QtWidgets.QGridLayout()
        self.gl_magnetic_field_data.setObjectName("gl_magnetic_field_data")
        self.gridLayout_3.addLayout(self.gl_magnetic_field_data, 0, 0, 1, 1)
        self.tab_show.addTab(self.tab_magnetic_field_data, "")
        self.tab_discretize = QtWidgets.QWidget()
        self.tab_discretize.setObjectName("tab_discretize")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_discretize)
        self.gridLayout.setObjectName("gridLayout")
        self.gl_discretize = QtWidgets.QGridLayout()
        self.gl_discretize.setObjectName("gl_discretize")
        self.gridLayout.addLayout(self.gl_discretize, 0, 0, 1, 1)
        self.tab_show.addTab(self.tab_discretize, "")
        self.tab_sample_data_t = QtWidgets.QWidget()
        self.tab_sample_data_t.setObjectName("tab_sample_data_t")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_sample_data_t)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gl_sample_data_t = QtWidgets.QGridLayout()
        self.gl_sample_data_t.setObjectName("gl_sample_data_t")
        self.gridLayout_27.addLayout(self.gl_sample_data_t, 0, 0, 1, 1)
        self.tab_show.addTab(self.tab_sample_data_t, "")
        self.tab_classification_result_t = QtWidgets.QWidget()
        self.tab_classification_result_t.setObjectName("tab_classification_result_t")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_classification_result_t)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gl_classification_result_t = QtWidgets.QGridLayout()
        self.gl_classification_result_t.setObjectName("gl_classification_result_t")
        self.gridLayout_28.addLayout(self.gl_classification_result_t, 0, 0, 1, 1)
        self.tab_show.addTab(self.tab_classification_result_t, "")
        self.verticalLayout.addWidget(self.tab_show)
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tb_output_box = QtWidgets.QTextBrowser(self.groupBox_10)
        self.tb_output_box.setAutoFillBackground(False)
        self.tb_output_box.setObjectName("tb_output_box")
        self.gridLayout_4.addWidget(self.tb_output_box, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.pb_run_tdem_classification = QtWidgets.QPushButton(self.widget_2)
        self.pb_run_tdem_classification.setGeometry(QtCore.QRect(280, 60, 206, 31))
        self.pb_run_tdem_classification.setObjectName("pb_run_tdem_classification")
        self.pbar_rfi = QtWidgets.QProgressBar(self.widget_2)
        self.pbar_rfi.setGeometry(QtCore.QRect(280, 40, 205, 6))
        self.pbar_rfi.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #FFFFFF;}QProgressBar::chunk {   background-color: #007FFF;   width: 10px;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.pbar_rfi.setMaximum(0)
        self.pbar_rfi.setProperty("value", -1)
        self.pbar_rfi.setTextVisible(False)
        self.pbar_rfi.setObjectName("pbar_rfi")
        self.pb_run_fdem_forward_simulation = QtWidgets.QPushButton(self.widget_2)
        self.pb_run_fdem_forward_simulation.setGeometry(QtCore.QRect(0, 60, 211, 31))
        self.pb_run_fdem_forward_simulation.setObjectName("pb_run_fdem_forward_simulation")
        self.pb_run_fdem_inversion = QtWidgets.QPushButton(self.widget_2)
        self.pb_run_fdem_inversion.setGeometry(QtCore.QRect(280, 60, 206, 31))
        self.pb_run_fdem_inversion.setObjectName("pb_run_fdem_inversion")
        self.pb_run_tdem_forward_simulation = QtWidgets.QPushButton(self.widget_2)
        self.pb_run_tdem_forward_simulation.setGeometry(QtCore.QRect(0, 60, 211, 31))
        self.pb_run_tdem_forward_simulation.setObjectName("pb_run_tdem_forward_simulation")
        self.pbar_rfs = QtWidgets.QProgressBar(self.widget_2)
        self.pbar_rfs.setGeometry(QtCore.QRect(0, 40, 205, 6))
        self.pbar_rfs.setStyleSheet("QProgressBar {   border: 2px solid grey;   border-radius: 5px;   background-color: #FFFFFF;}QProgressBar::chunk {   background-color: #007FFF;   width: 10px;}QProgressBar {   border: 2px solid grey;   border-radius: 5px;   text-align: center;}")
        self.pbar_rfs.setMaximum(0)
        self.pbar_rfs.setProperty("value", -1)
        self.pbar_rfs.setTextVisible(False)
        self.pbar_rfs.setObjectName("pbar_rfs")
        self.pb_run_tdem_forward_simulation.raise_()
        self.pb_run_tdem_classification.raise_()
        self.pbar_rfi.raise_()
        self.pb_run_fdem_forward_simulation.raise_()
        self.pb_run_fdem_inversion.raise_()
        self.pbar_rfs.raise_()
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout_6.addWidget(self.widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tab_signal_type = QtWidgets.QTabWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tab_signal_type.setFont(font)
        self.tab_signal_type.setAutoFillBackground(True)
        self.tab_signal_type.setObjectName("tab_signal_type")
        self.tab_FDEM = QtWidgets.QWidget()
        self.tab_FDEM.setAutoFillBackground(True)
        self.tab_FDEM.setObjectName("tab_FDEM")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_FDEM)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_5 = QtWidgets.QWidget(self.tab_FDEM)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_139 = QtWidgets.QLabel(self.groupBox_2)
        self.label_139.setAlignment(QtCore.Qt.AlignCenter)
        self.label_139.setObjectName("label_139")
        self.gridLayout_14.addWidget(self.label_139, 0, 0, 1, 1)
        self.cb_optimization_algorithm = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_optimization_algorithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_optimization_algorithm.setObjectName("cb_optimization_algorithm")
        self.cb_optimization_algorithm.addItem("")
        self.cb_optimization_algorithm.addItem("")
        self.cb_optimization_algorithm.addItem("")
        self.cb_optimization_algorithm.addItem("")
        self.gridLayout_14.addWidget(self.cb_optimization_algorithm, 0, 1, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.groupBox_2)
        self.label_141.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_141.setObjectName("label_141")
        self.gridLayout_14.addWidget(self.label_141, 0, 2, 1, 1)
        self.le_optimization_tol = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_optimization_tol.setAlignment(QtCore.Qt.AlignCenter)
        self.le_optimization_tol.setObjectName("le_optimization_tol")
        self.gridLayout_14.addWidget(self.le_optimization_tol, 0, 3, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.groupBox_2)
        self.label_140.setAlignment(QtCore.Qt.AlignCenter)
        self.label_140.setObjectName("label_140")
        self.gridLayout_14.addWidget(self.label_140, 1, 0, 1, 1)
        self.le_optimization_iterations = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_optimization_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.le_optimization_iterations.setObjectName("le_optimization_iterations")
        self.gridLayout_14.addWidget(self.le_optimization_iterations, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_99 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_99.setFont(font)
        self.label_99.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_99.setScaledContents(False)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.gridLayout_11.addWidget(self.label_99, 0, 0, 1, 1)
        self.le_detector_radius = QtWidgets.QLineEdit(self.groupBox_12)
        self.le_detector_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_radius.setObjectName("le_detector_radius")
        self.gridLayout_11.addWidget(self.le_detector_radius, 0, 1, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.groupBox_12)
        self.label_104.setObjectName("label_104")
        self.gridLayout_11.addWidget(self.label_104, 0, 2, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.groupBox_12)
        self.label_97.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_97.setScaledContents(False)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.gridLayout_11.addWidget(self.label_97, 0, 3, 1, 1)
        self.le_detector_current = QtWidgets.QLineEdit(self.groupBox_12)
        self.le_detector_current.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_current.setObjectName("le_detector_current")
        self.gridLayout_11.addWidget(self.le_detector_current, 0, 4, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.groupBox_12)
        self.label_100.setObjectName("label_100")
        self.gridLayout_11.addWidget(self.label_100, 0, 5, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.groupBox_12)
        self.label_98.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_98.setScaledContents(False)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.gridLayout_11.addWidget(self.label_98, 0, 6, 1, 1)
        self.le_detector_frequency = QtWidgets.QLineEdit(self.groupBox_12)
        self.le_detector_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_frequency.setObjectName("le_detector_frequency")
        self.gridLayout_11.addWidget(self.le_detector_frequency, 0, 7, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.groupBox_12)
        self.label_96.setObjectName("label_96")
        self.gridLayout_11.addWidget(self.label_96, 0, 8, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.groupBox_12)
        self.label_103.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_103.setScaledContents(False)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.gridLayout_11.addWidget(self.label_103, 1, 0, 1, 1)
        self.le_detector_pitch = QtWidgets.QLineEdit(self.groupBox_12)
        self.le_detector_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_pitch.setObjectName("le_detector_pitch")
        self.gridLayout_11.addWidget(self.le_detector_pitch, 1, 1, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.groupBox_12)
        self.label_101.setObjectName("label_101")
        self.gridLayout_11.addWidget(self.label_101, 1, 2, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.groupBox_12)
        self.label_105.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_105.setScaledContents(False)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.gridLayout_11.addWidget(self.label_105, 1, 3, 1, 1)
        self.le_detector_roll = QtWidgets.QLineEdit(self.groupBox_12)
        self.le_detector_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_roll.setObjectName("le_detector_roll")
        self.gridLayout_11.addWidget(self.le_detector_roll, 1, 4, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.groupBox_12)
        self.label_102.setObjectName("label_102")
        self.gridLayout_11.addWidget(self.label_102, 1, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_131 = QtWidgets.QLabel(self.groupBox_14)
        self.label_131.setAlignment(QtCore.Qt.AlignCenter)
        self.label_131.setObjectName("label_131")
        self.gridLayout_13.addWidget(self.label_131, 0, 0, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.groupBox_14)
        self.label_133.setAlignment(QtCore.Qt.AlignCenter)
        self.label_133.setObjectName("label_133")
        self.gridLayout_13.addWidget(self.label_133, 0, 5, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.groupBox_14)
        self.label_135.setAlignment(QtCore.Qt.AlignCenter)
        self.label_135.setObjectName("label_135")
        self.gridLayout_13.addWidget(self.label_135, 0, 10, 1, 1)
        self.le_collection_SNR = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_SNR.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_SNR.setObjectName("le_collection_SNR")
        self.gridLayout_13.addWidget(self.le_collection_SNR, 0, 11, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.groupBox_14)
        self.label_136.setObjectName("label_136")
        self.gridLayout_13.addWidget(self.label_136, 0, 12, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.groupBox_14)
        self.label_126.setAlignment(QtCore.Qt.AlignCenter)
        self.label_126.setObjectName("label_126")
        self.gridLayout_13.addWidget(self.label_126, 1, 0, 1, 1)
        self.le_collection_x_min = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_x_min.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_x_min.setObjectName("le_collection_x_min")
        self.gridLayout_13.addWidget(self.le_collection_x_min, 1, 1, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.groupBox_14)
        self.label_127.setObjectName("label_127")
        self.gridLayout_13.addWidget(self.label_127, 1, 2, 1, 1)
        self.le_collection_x_max = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_x_max.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_x_max.setObjectName("le_collection_x_max")
        self.gridLayout_13.addWidget(self.le_collection_x_max, 1, 3, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.groupBox_14)
        self.label_137.setObjectName("label_137")
        self.gridLayout_13.addWidget(self.label_137, 1, 4, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.groupBox_14)
        self.label_128.setAlignment(QtCore.Qt.AlignCenter)
        self.label_128.setObjectName("label_128")
        self.gridLayout_13.addWidget(self.label_128, 1, 5, 1, 1)
        self.le_collection_y_min = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_y_min.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_y_min.setObjectName("le_collection_y_min")
        self.gridLayout_13.addWidget(self.le_collection_y_min, 1, 6, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.groupBox_14)
        self.label_129.setObjectName("label_129")
        self.gridLayout_13.addWidget(self.label_129, 1, 7, 1, 1)
        self.le_collection_y_max = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_y_max.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_y_max.setObjectName("le_collection_y_max")
        self.gridLayout_13.addWidget(self.le_collection_y_max, 1, 8, 1, 1)
        self.label_130 = QtWidgets.QLabel(self.groupBox_14)
        self.label_130.setObjectName("label_130")
        self.gridLayout_13.addWidget(self.label_130, 1, 9, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.groupBox_14)
        self.label_138.setAlignment(QtCore.Qt.AlignCenter)
        self.label_138.setObjectName("label_138")
        self.gridLayout_13.addWidget(self.label_138, 1, 10, 1, 1)
        self.cb_collection_direction = QtWidgets.QComboBox(self.groupBox_14)
        self.cb_collection_direction.setAutoFillBackground(False)
        self.cb_collection_direction.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cb_collection_direction.setObjectName("cb_collection_direction")
        self.cb_collection_direction.addItem("")
        self.cb_collection_direction.addItem("")
        self.cb_collection_direction.addItem("")
        self.cb_collection_direction.addItem("")
        self.gridLayout_13.addWidget(self.cb_collection_direction, 1, 11, 1, 1)
        self.le_collection_height = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_height.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_height.setObjectName("le_collection_height")
        self.gridLayout_13.addWidget(self.le_collection_height, 0, 6, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.groupBox_14)
        self.label_134.setObjectName("label_134")
        self.gridLayout_13.addWidget(self.label_134, 0, 7, 1, 1)
        self.le_collection_spacing = QtWidgets.QLineEdit(self.groupBox_14)
        self.le_collection_spacing.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_spacing.setObjectName("le_collection_spacing")
        self.gridLayout_13.addWidget(self.le_collection_spacing, 0, 1, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.groupBox_14)
        self.label_132.setObjectName("label_132")
        self.gridLayout_13.addWidget(self.label_132, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_14, 2, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_118 = QtWidgets.QLabel(self.groupBox_13)
        self.label_118.setAlignment(QtCore.Qt.AlignCenter)
        self.label_118.setObjectName("label_118")
        self.gridLayout_12.addWidget(self.label_118, 0, 0, 1, 1)
        self.le_target_conductivity = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_conductivity.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_conductivity.setObjectName("le_target_conductivity")
        self.gridLayout_12.addWidget(self.le_target_conductivity, 0, 1, 1, 2)
        self.label_119 = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(8)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.gridLayout_12.addWidget(self.label_119, 0, 3, 1, 2)
        self.label_112 = QtWidgets.QLabel(self.groupBox_13)
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.gridLayout_12.addWidget(self.label_112, 0, 5, 1, 2)
        self.le_target_permeability = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_permeability.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_permeability.setObjectName("le_target_permeability")
        self.gridLayout_12.addWidget(self.le_target_permeability, 0, 7, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(8)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_113.setFont(font)
        self.label_113.setObjectName("label_113")
        self.gridLayout_12.addWidget(self.label_113, 0, 8, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.groupBox_13)
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setObjectName("label_120")
        self.gridLayout_12.addWidget(self.label_120, 0, 9, 1, 1)
        self.le_target_radius = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_radius.setObjectName("le_target_radius")
        self.gridLayout_12.addWidget(self.le_target_radius, 0, 10, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.groupBox_13)
        self.label_121.setObjectName("label_121")
        self.gridLayout_12.addWidget(self.label_121, 0, 11, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.groupBox_13)
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.gridLayout_12.addWidget(self.label_122, 1, 0, 1, 1)
        self.le_target_pitch = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_pitch.setObjectName("le_target_pitch")
        self.gridLayout_12.addWidget(self.le_target_pitch, 1, 1, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.groupBox_13)
        self.label_123.setObjectName("label_123")
        self.gridLayout_12.addWidget(self.label_123, 1, 2, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.groupBox_13)
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.gridLayout_12.addWidget(self.label_116, 1, 6, 1, 1)
        self.le_target_roll = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_roll.setObjectName("le_target_roll")
        self.gridLayout_12.addWidget(self.le_target_roll, 1, 7, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.groupBox_13)
        self.label_117.setObjectName("label_117")
        self.gridLayout_12.addWidget(self.label_117, 1, 8, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.groupBox_13)
        self.label_114.setAlignment(QtCore.Qt.AlignCenter)
        self.label_114.setObjectName("label_114")
        self.gridLayout_12.addWidget(self.label_114, 1, 9, 1, 1)
        self.le_target_length = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_length.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_length.setObjectName("le_target_length")
        self.gridLayout_12.addWidget(self.le_target_length, 1, 10, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.groupBox_13)
        self.label_115.setObjectName("label_115")
        self.gridLayout_12.addWidget(self.label_115, 1, 11, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.groupBox_13)
        self.label_124.setAlignment(QtCore.Qt.AlignCenter)
        self.label_124.setObjectName("label_124")
        self.gridLayout_12.addWidget(self.label_124, 2, 0, 1, 1)
        self.le_target_position_x = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_position_x.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_position_x.setObjectName("le_target_position_x")
        self.gridLayout_12.addWidget(self.le_target_position_x, 2, 1, 1, 1)
        self.le_target_position_y = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_position_y.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_position_y.setObjectName("le_target_position_y")
        self.gridLayout_12.addWidget(self.le_target_position_y, 2, 2, 1, 2)
        self.le_target_position_z = QtWidgets.QLineEdit(self.groupBox_13)
        self.le_target_position_z.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_position_z.setObjectName("le_target_position_z")
        self.gridLayout_12.addWidget(self.le_target_position_z, 2, 4, 1, 2)
        self.label_111 = QtWidgets.QLabel(self.groupBox_13)
        self.label_111.setObjectName("label_111")
        self.gridLayout_12.addWidget(self.label_111, 2, 6, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.cb_func_save_data = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_func_save_data.setObjectName("cb_func_save_data")
        self.gridLayout_16.addWidget(self.cb_func_save_data, 0, 0, 1, 1)
        self.cb_func_save_result = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_func_save_result.setObjectName("cb_func_save_result")
        self.gridLayout_16.addWidget(self.cb_func_save_result, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.gridLayout_10.setRowMinimumHeight(0, 4)
        self.gridLayout_10.setRowMinimumHeight(1, 1)
        self.gridLayout_10.setRowMinimumHeight(2, 1)
        self.gridLayout_10.setRowStretch(0, 7)
        self.gridLayout_10.setRowStretch(1, 2)
        self.gridLayout_10.setRowStretch(2, 1)
        self.gridLayout_9.addWidget(self.widget_5, 0, 0, 1, 1)
        self.tab_signal_type.addTab(self.tab_FDEM, "")
        self.tab_TDEM = QtWidgets.QWidget()
        self.tab_TDEM.setAutoFillBackground(True)
        self.tab_TDEM.setObjectName("tab_TDEM")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.tab_TDEM)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.widget_6 = QtWidgets.QWidget(self.tab_TDEM)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_142 = QtWidgets.QLabel(self.groupBox_5)
        self.label_142.setAlignment(QtCore.Qt.AlignCenter)
        self.label_142.setObjectName("label_142")
        self.gridLayout_19.addWidget(self.label_142, 0, 0, 1, 1)
        self.cb_dr_algorithm_t = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_dr_algorithm_t.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_dr_algorithm_t.setObjectName("cb_dr_algorithm_t")
        self.cb_dr_algorithm_t.addItem("")
        self.cb_dr_algorithm_t.addItem("")
        self.gridLayout_19.addWidget(self.cb_dr_algorithm_t, 0, 1, 1, 1)
        self.label_143 = QtWidgets.QLabel(self.groupBox_5)
        self.label_143.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_143.setAlignment(QtCore.Qt.AlignCenter)
        self.label_143.setObjectName("label_143")
        self.gridLayout_19.addWidget(self.label_143, 0, 2, 1, 1)
        self.cb_dr_task_t = QtWidgets.QComboBox(self.groupBox_5)
        self.cb_dr_task_t.setObjectName("cb_dr_task_t")
        self.cb_dr_task_t.addItem("")
        self.cb_dr_task_t.addItem("")
        self.gridLayout_19.addWidget(self.cb_dr_task_t, 0, 3, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_150 = QtWidgets.QLabel(self.groupBox_7)
        self.label_150.setAlignment(QtCore.Qt.AlignCenter)
        self.label_150.setObjectName("label_150")
        self.gridLayout_26.addWidget(self.label_150, 0, 0, 1, 1)
        self.cb_cls_algorithm_t = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_cls_algorithm_t.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_cls_algorithm_t.setObjectName("cb_cls_algorithm_t")
        self.cb_cls_algorithm_t.addItem("")
        self.gridLayout_26.addWidget(self.cb_cls_algorithm_t, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_26.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_26.addWidget(self.label_2, 0, 3, 1, 1)
        self.gridLayout_26.setColumnStretch(0, 4)
        self.gridLayout_26.setColumnStretch(1, 5)
        self.gridLayout_26.setColumnStretch(2, 4)
        self.gridLayout_26.setColumnStretch(3, 4)
        self.gridLayout_18.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.gridLayout_18.setRowMinimumHeight(0, 1)
        self.gridLayout_18.setRowMinimumHeight(1, 1)
        self.gridLayout_17.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.le_detector_roll_t = QtWidgets.QLineEdit(self.groupBox_16)
        self.le_detector_roll_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_roll_t.setObjectName("le_detector_roll_t")
        self.gridLayout_21.addWidget(self.le_detector_roll_t, 1, 4, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_106.setFont(font)
        self.label_106.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_106.setScaledContents(False)
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName("label_106")
        self.gridLayout_21.addWidget(self.label_106, 0, 0, 1, 1)
        self.label_145 = QtWidgets.QLabel(self.groupBox_16)
        self.label_145.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_145.setScaledContents(False)
        self.label_145.setAlignment(QtCore.Qt.AlignCenter)
        self.label_145.setObjectName("label_145")
        self.gridLayout_21.addWidget(self.label_145, 1, 0, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.groupBox_16)
        self.label_147.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_147.setScaledContents(False)
        self.label_147.setAlignment(QtCore.Qt.AlignCenter)
        self.label_147.setObjectName("label_147")
        self.gridLayout_21.addWidget(self.label_147, 1, 3, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.groupBox_16)
        self.label_109.setObjectName("label_109")
        self.gridLayout_21.addWidget(self.label_109, 0, 5, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.groupBox_16)
        self.label_146.setObjectName("label_146")
        self.gridLayout_21.addWidget(self.label_146, 1, 2, 1, 1)
        self.le_detector_current_t = QtWidgets.QLineEdit(self.groupBox_16)
        self.le_detector_current_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_current_t.setObjectName("le_detector_current_t")
        self.gridLayout_21.addWidget(self.le_detector_current_t, 0, 4, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.groupBox_16)
        self.label_148.setObjectName("label_148")
        self.gridLayout_21.addWidget(self.label_148, 1, 5, 1, 1)
        self.le_detector_pitch_t = QtWidgets.QLineEdit(self.groupBox_16)
        self.le_detector_pitch_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_pitch_t.setObjectName("le_detector_pitch_t")
        self.gridLayout_21.addWidget(self.le_detector_pitch_t, 1, 1, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.groupBox_16)
        self.label_108.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_108.setScaledContents(False)
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName("label_108")
        self.gridLayout_21.addWidget(self.label_108, 0, 3, 1, 1)
        self.le_detector_radius_t = QtWidgets.QLineEdit(self.groupBox_16)
        self.le_detector_radius_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_detector_radius_t.setObjectName("le_detector_radius_t")
        self.gridLayout_21.addWidget(self.le_detector_radius_t, 0, 1, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.groupBox_16)
        self.label_107.setObjectName("label_107")
        self.gridLayout_21.addWidget(self.label_107, 0, 2, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_152 = QtWidgets.QLabel(self.groupBox_17)
        self.label_152.setObjectName("label_152")
        self.gridLayout_22.addWidget(self.label_152, 0, 12, 1, 1)
        self.le_collection_SNR_t = QtWidgets.QLineEdit(self.groupBox_17)
        self.le_collection_SNR_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_SNR_t.setObjectName("le_collection_SNR_t")
        self.gridLayout_22.addWidget(self.le_collection_SNR_t, 0, 11, 1, 1)
        self.le_collection_split_t = QtWidgets.QLineEdit(self.groupBox_17)
        self.le_collection_split_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_collection_split_t.setObjectName("le_collection_split_t")
        self.gridLayout_22.addWidget(self.le_collection_split_t, 0, 1, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.groupBox_17)
        self.label_151.setAlignment(QtCore.Qt.AlignCenter)
        self.label_151.setObjectName("label_151")
        self.gridLayout_22.addWidget(self.label_151, 0, 10, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.groupBox_17)
        self.label_149.setAlignment(QtCore.Qt.AlignCenter)
        self.label_149.setObjectName("label_149")
        self.gridLayout_22.addWidget(self.label_149, 0, 0, 1, 1)
        self.label_161 = QtWidgets.QLabel(self.groupBox_17)
        self.label_161.setObjectName("label_161")
        self.gridLayout_22.addWidget(self.label_161, 0, 2, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_17, 2, 0, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_173 = QtWidgets.QLabel(self.groupBox_18)
        self.label_173.setObjectName("label_173")
        self.gridLayout_23.addWidget(self.label_173, 1, 4, 1, 1)
        self.le_target_a_max_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_a_max_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_a_max_t.setObjectName("le_target_a_max_t")
        self.gridLayout_23.addWidget(self.le_target_a_max_t, 1, 3, 1, 1)
        self.le_target_material_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_material_t.setEnabled(False)
        self.le_target_material_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_material_t.setObjectName("le_target_material_t")
        self.gridLayout_23.addWidget(self.le_target_material_t, 0, 1, 1, 1)
        self.label_168 = QtWidgets.QLabel(self.groupBox_18)
        self.label_168.setAlignment(QtCore.Qt.AlignCenter)
        self.label_168.setObjectName("label_168")
        self.gridLayout_23.addWidget(self.label_168, 1, 0, 1, 1)
        self.le_target_a_min_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_a_min_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_a_min_t.setObjectName("le_target_a_min_t")
        self.gridLayout_23.addWidget(self.le_target_a_min_t, 1, 1, 1, 1)
        self.label_157 = QtWidgets.QLabel(self.groupBox_18)
        self.label_157.setObjectName("label_157")
        self.gridLayout_23.addWidget(self.label_157, 1, 2, 1, 1)
        self.label_162 = QtWidgets.QLabel(self.groupBox_18)
        self.label_162.setAlignment(QtCore.Qt.AlignCenter)
        self.label_162.setObjectName("label_162")
        self.gridLayout_23.addWidget(self.label_162, 0, 0, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.groupBox_18)
        self.label_153.setAlignment(QtCore.Qt.AlignCenter)
        self.label_153.setObjectName("label_153")
        self.gridLayout_23.addWidget(self.label_153, 3, 4, 1, 1)
        self.label_170 = QtWidgets.QLabel(self.groupBox_18)
        self.label_170.setAlignment(QtCore.Qt.AlignCenter)
        self.label_170.setObjectName("label_170")
        self.gridLayout_23.addWidget(self.label_170, 1, 5, 1, 1)
        self.label_158 = QtWidgets.QLabel(self.groupBox_18)
        self.label_158.setObjectName("label_158")
        self.gridLayout_23.addWidget(self.label_158, 3, 2, 1, 1)
        self.le_target_b_min_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_b_min_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_b_min_t.setObjectName("le_target_b_min_t")
        self.gridLayout_23.addWidget(self.le_target_b_min_t, 3, 1, 1, 1)
        self.le_target_b_max_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_b_max_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_b_max_t.setObjectName("le_target_b_max_t")
        self.gridLayout_23.addWidget(self.le_target_b_max_t, 3, 3, 1, 1)
        self.le_target_b_split_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_b_split_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_b_split_t.setObjectName("le_target_b_split_t")
        self.gridLayout_23.addWidget(self.le_target_b_split_t, 3, 6, 1, 1)
        self.label_156 = QtWidgets.QLabel(self.groupBox_18)
        self.label_156.setAlignment(QtCore.Qt.AlignCenter)
        self.label_156.setObjectName("label_156")
        self.gridLayout_23.addWidget(self.label_156, 3, 0, 1, 1)
        self.le_target_a_split_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_a_split_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_a_split_t.setObjectName("le_target_a_split_t")
        self.gridLayout_23.addWidget(self.le_target_a_split_t, 1, 6, 1, 1)
        self.label_172 = QtWidgets.QLabel(self.groupBox_18)
        self.label_172.setAlignment(QtCore.Qt.AlignCenter)
        self.label_172.setObjectName("label_172")
        self.gridLayout_23.addWidget(self.label_172, 3, 5, 1, 1)
        self.label_164 = QtWidgets.QLabel(self.groupBox_18)
        self.label_164.setAlignment(QtCore.Qt.AlignCenter)
        self.label_164.setObjectName("label_164")
        self.gridLayout_23.addWidget(self.label_164, 0, 2, 1, 1)
        self.le_target_shape_t = QtWidgets.QLineEdit(self.groupBox_18)
        self.le_target_shape_t.setEnabled(False)
        self.le_target_shape_t.setAlignment(QtCore.Qt.AlignCenter)
        self.le_target_shape_t.setObjectName("le_target_shape_t")
        self.gridLayout_23.addWidget(self.le_target_shape_t, 0, 3, 1, 4)
        self.gridLayout_20.addWidget(self.groupBox_18, 1, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.cb_func_save_data_t = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_func_save_data_t.setObjectName("cb_func_save_data_t")
        self.gridLayout_24.addWidget(self.cb_func_save_data_t, 0, 0, 1, 1)
        self.cb_func_save_result_t = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_func_save_result_t.setObjectName("cb_func_save_result_t")
        self.gridLayout_24.addWidget(self.cb_func_save_result_t, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.gridLayout_17.setRowStretch(0, 6)
        self.gridLayout_17.setRowStretch(1, 6)
        self.gridLayout_17.setRowStretch(2, 2)
        self.gridLayout_25.addWidget(self.widget_6, 0, 0, 1, 1)
        self.tab_signal_type.addTab(self.tab_TDEM, "")
        self.gridLayout_5.addWidget(self.tab_signal_type, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 3)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_7.addWidget(self.widget_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1329, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuLanguage = QtWidgets.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionChinese = QtWidgets.QAction(MainWindow)
        self.actionChinese.setObjectName("actionChinese")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionChinese)
        self.menuHelp.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_show.setCurrentIndex(2)
        self.tab_signal_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_show.setTabText(self.tab_show.indexOf(self.tab_detection_scenario), _translate("MainWindow", "Detection scenario"))
        self.tab_show.setTabText(self.tab_show.indexOf(self.tab_magnetic_field_data), _translate("MainWindow", "Magnetic field data"))
        self.tab_show.setTabText(self.tab_show.indexOf(self.tab_discretize), _translate("MainWindow", "Inversion result"))
        self.tab_show.setTabText(self.tab_show.indexOf(self.tab_sample_data_t), _translate("MainWindow", "Sample response data"))
        self.tab_show.setTabText(self.tab_show.indexOf(self.tab_classification_result_t), _translate("MainWindow", "Classification result"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Output"))
        self.pb_run_tdem_classification.setText(_translate("MainWindow", "Run TDEM classification"))
        self.pb_run_fdem_forward_simulation.setText(_translate("MainWindow", "Run forward simulation"))
        self.pb_run_fdem_inversion.setText(_translate("MainWindow", "Run FDEM inversion"))
        self.pb_run_tdem_forward_simulation.setText(_translate("MainWindow", "Run forward simulation"))
        self.groupBox.setTitle(_translate("MainWindow", "Inversion"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Optimization algorithm parameters"))
        self.label_139.setText(_translate("MainWindow", "Algorithm"))
        self.cb_optimization_algorithm.setItemText(0, _translate("MainWindow", "Levenberg-Marquardt"))
        self.cb_optimization_algorithm.setItemText(1, _translate("MainWindow", "BFGS"))
        self.cb_optimization_algorithm.setItemText(2, _translate("MainWindow", "Conjugate gradient"))
        self.cb_optimization_algorithm.setItemText(3, _translate("MainWindow", "Steepest descent"))
        self.label_141.setText(_translate("MainWindow", "Tolerance:    gradient  < "))
        self.le_optimization_tol.setText(_translate("MainWindow", "1e-9"))
        self.label_140.setText(_translate("MainWindow", "Iterations"))
        self.le_optimization_iterations.setText(_translate("MainWindow", "1000"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Forward simulation"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Detector parameters"))
        self.label_99.setText(_translate("MainWindow", "Radius"))
        self.le_detector_radius.setText(_translate("MainWindow", "0.4"))
        self.label_104.setText(_translate("MainWindow", "m"))
        self.label_97.setText(_translate("MainWindow", "Current"))
        self.le_detector_current.setText(_translate("MainWindow", "20"))
        self.label_100.setText(_translate("MainWindow", "A"))
        self.label_98.setText(_translate("MainWindow", "Frequency"))
        self.le_detector_frequency.setText(_translate("MainWindow", "1000"))
        self.label_96.setText(_translate("MainWindow", "Hz"))
        self.label_103.setText(_translate("MainWindow", "Pitch"))
        self.le_detector_pitch.setText(_translate("MainWindow", "0"))
        self.label_101.setText(_translate("MainWindow", "°"))
        self.label_105.setText(_translate("MainWindow", "Roll"))
        self.le_detector_roll.setText(_translate("MainWindow", "0"))
        self.label_102.setText(_translate("MainWindow", "°"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Collection parameters"))
        self.label_131.setText(_translate("MainWindow", "Spacing"))
        self.label_133.setText(_translate("MainWindow", "Height"))
        self.label_135.setText(_translate("MainWindow", "SNR"))
        self.le_collection_SNR.setText(_translate("MainWindow", "30"))
        self.label_136.setText(_translate("MainWindow", "dB"))
        self.label_126.setText(_translate("MainWindow", "x"))
        self.le_collection_x_min.setText(_translate("MainWindow", "-2"))
        self.label_127.setText(_translate("MainWindow", "-"))
        self.le_collection_x_max.setText(_translate("MainWindow", "2"))
        self.label_137.setText(_translate("MainWindow", "m"))
        self.label_128.setText(_translate("MainWindow", "y"))
        self.le_collection_y_min.setText(_translate("MainWindow", "-2"))
        self.label_129.setText(_translate("MainWindow", "-"))
        self.le_collection_y_max.setText(_translate("MainWindow", "2"))
        self.label_130.setText(_translate("MainWindow", "m"))
        self.label_138.setText(_translate("MainWindow", "Field"))
        self.cb_collection_direction.setItemText(0, _translate("MainWindow", "z-axis"))
        self.cb_collection_direction.setItemText(1, _translate("MainWindow", "x-axis"))
        self.cb_collection_direction.setItemText(2, _translate("MainWindow", "y-axis"))
        self.cb_collection_direction.setItemText(3, _translate("MainWindow", "Total"))
        self.le_collection_height.setText(_translate("MainWindow", "0.1"))
        self.label_134.setText(_translate("MainWindow", "m"))
        self.le_collection_spacing.setText(_translate("MainWindow", "0.4"))
        self.label_132.setText(_translate("MainWindow", "m"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Target parameters (cylinder)"))
        self.label_118.setText(_translate("MainWindow", "Conductivity"))
        self.le_target_conductivity.setText(_translate("MainWindow", "5.71e7"))
        self.label_119.setText(_translate("MainWindow", "S/m"))
        self.label_112.setText(_translate("MainWindow", "Permeability"))
        self.le_target_permeability.setText(_translate("MainWindow", "1.26e-6"))
        self.label_113.setText(_translate("MainWindow", "H/m"))
        self.label_120.setText(_translate("MainWindow", "Radius"))
        self.le_target_radius.setText(_translate("MainWindow", "0.2"))
        self.label_121.setText(_translate("MainWindow", "m"))
        self.label_122.setText(_translate("MainWindow", "Pitch"))
        self.le_target_pitch.setText(_translate("MainWindow", "0"))
        self.label_123.setText(_translate("MainWindow", "°"))
        self.label_116.setText(_translate("MainWindow", "Roll"))
        self.le_target_roll.setText(_translate("MainWindow", "0"))
        self.label_117.setText(_translate("MainWindow", "°"))
        self.label_114.setText(_translate("MainWindow", "Length"))
        self.le_target_length.setText(_translate("MainWindow", "1"))
        self.label_115.setText(_translate("MainWindow", "m"))
        self.label_124.setText(_translate("MainWindow", "Position"))
        self.le_target_position_x.setText(_translate("MainWindow", "0"))
        self.le_target_position_y.setText(_translate("MainWindow", "0"))
        self.le_target_position_z.setText(_translate("MainWindow", "-5"))
        self.label_111.setText(_translate("MainWindow", "m"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Other functions"))
        self.cb_func_save_data.setText(_translate("MainWindow", "Save field data"))
        self.cb_func_save_result.setText(_translate("MainWindow", "Save inversion results"))
        self.tab_signal_type.setTabText(self.tab_signal_type.indexOf(self.tab_FDEM), _translate("MainWindow", "FDEM detection"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Classification"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Dimension reduction algorithm"))
        self.label_142.setText(_translate("MainWindow", "Algorithm"))
        self.cb_dr_algorithm_t.setItemText(0, _translate("MainWindow", "SF"))
        self.cb_dr_algorithm_t.setItemText(1, _translate("MainWindow", "None"))
        self.label_143.setText(_translate("MainWindow", "task"))
        self.cb_dr_task_t.setItemText(0, _translate("MainWindow", "material"))
        self.cb_dr_task_t.setItemText(1, _translate("MainWindow", "shape"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Classification algorithm"))
        self.label_150.setText(_translate("MainWindow", "Algorithm"))
        self.cb_cls_algorithm_t.setItemText(0, _translate("MainWindow", "ANN"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Forward simulation"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Detector parameters"))
        self.le_detector_roll_t.setText(_translate("MainWindow", "0"))
        self.label_106.setText(_translate("MainWindow", "Radius"))
        self.label_145.setText(_translate("MainWindow", "Pitch"))
        self.label_147.setText(_translate("MainWindow", "Roll"))
        self.label_109.setText(_translate("MainWindow", "A"))
        self.label_146.setText(_translate("MainWindow", "°"))
        self.le_detector_current_t.setText(_translate("MainWindow", "20"))
        self.label_148.setText(_translate("MainWindow", "°"))
        self.le_detector_pitch_t.setText(_translate("MainWindow", "0"))
        self.label_108.setText(_translate("MainWindow", "Current"))
        self.le_detector_radius_t.setText(_translate("MainWindow", "0.4"))
        self.label_107.setText(_translate("MainWindow", "m"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Collection parameters"))
        self.label_152.setText(_translate("MainWindow", "dB"))
        self.le_collection_SNR_t.setText(_translate("MainWindow", "35"))
        self.le_collection_split_t.setText(_translate("MainWindow", "20"))
        self.label_151.setText(_translate("MainWindow", "SNR"))
        self.label_149.setText(_translate("MainWindow", "t_split"))
        self.label_161.setText(_translate("MainWindow", "/s"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Target parameters (spheroid)"))
        self.label_173.setText(_translate("MainWindow", "m"))
        self.le_target_a_max_t.setText(_translate("MainWindow", "1.5"))
        self.le_target_material_t.setText(_translate("MainWindow", "Steel,Ni,Al"))
        self.label_168.setText(_translate("MainWindow", "ta"))
        self.le_target_a_min_t.setText(_translate("MainWindow", "0.01"))
        self.label_157.setText(_translate("MainWindow", "——"))
        self.label_162.setText(_translate("MainWindow", "material"))
        self.label_153.setText(_translate("MainWindow", "m"))
        self.label_170.setText(_translate("MainWindow", "a_split"))
        self.label_158.setText(_translate("MainWindow", "——"))
        self.le_target_b_min_t.setText(_translate("MainWindow", "0.01"))
        self.le_target_b_max_t.setText(_translate("MainWindow", "1.5"))
        self.le_target_b_split_t.setText(_translate("MainWindow", "0.08"))
        self.label_156.setText(_translate("MainWindow", "tb"))
        self.le_target_a_split_t.setText(_translate("MainWindow", "0.08"))
        self.label_172.setText(_translate("MainWindow", "b_split"))
        self.label_164.setText(_translate("MainWindow", "shape"))
        self.le_target_shape_t.setText(_translate("MainWindow", "Oblate spheroid,Prolate spheroid"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Other functions"))
        self.cb_func_save_data_t.setText(_translate("MainWindow", "Save response data"))
        self.cb_func_save_result_t.setText(_translate("MainWindow", "Save classification results"))
        self.tab_signal_type.setTabText(self.tab_signal_type.indexOf(self.tab_TDEM), _translate("MainWindow", "TDEM detection"))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionChinese.setText(_translate("MainWindow", "Chinese"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))

